<?php
require_once __DIR__ . '/../src/partials.php';
$pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf();$action=$_POST['action']??'';
 try{
  if($action==='save'){
   $id=(int)($_POST['id']??0);$device=(int)($_POST['device_id']??0);$title=trim($_POST['title']??'');$problem=trim($_POST['problem']??'');$solution=trim($_POST['solution']??'');$status=$_POST['status']??'Open';$cost=(float)($_POST['cost']??0);$note=trim($_POST['note']??'');
   if(!$device||$title==='')throw new Exception('กรุณาเลือกอุปกรณ์และระบุหัวข้องานซ่อม');if(!in_array($status,['Open','In Progress','Waiting Parts','Completed','Cancelled'],true))$status='Open';
   if($id){$s=$pdo->prepare('UPDATE maintenance_jobs SET device_id=?,title=?,problem=?,solution=?,status=?,cost=?,note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([$device,$title,$problem,$solution,$status,$cost,$note,$id]);flash('success','แก้ไขงานซ่อมเรียบร้อย');}
   else{$s=$pdo->prepare('INSERT INTO maintenance_jobs(device_id,title,problem,solution,status,cost,note,opened_by) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$device,$title,$problem,$solution,$status,$cost,$note,current_user_id()]);flash('success','เปิดงานซ่อมเรียบร้อย');}
  }elseif($action==='delete'){require_admin();$pdo->prepare('DELETE FROM maintenance_jobs WHERE id=?')->execute([(int)$_POST['id']]);flash('success','ลบงานซ่อมเรียบร้อย');}
 }catch(Throwable $e){flash('danger',$e->getMessage());}header('Location: /maintenance.php');exit;
}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM maintenance_jobs WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}
$devices=$pdo->query("SELECT id,device_name,model,imei FROM devices ORDER BY device_name,model")->fetchAll();$jobs=$pdo->query("SELECT m.*,d.device_name,d.model,d.imei,u.full_name FROM maintenance_jobs m JOIN devices d ON d.id=m.device_id LEFT JOIN users u ON u.id=m.opened_by ORDER BY m.id DESC")->fetchAll();
$stats=$pdo->query("SELECT COUNT(*) total, COUNT(*) FILTER(WHERE status IN ('Open','In Progress','Waiting Parts')) open_count, COALESCE(SUM(cost),0) cost_total FROM maintenance_jobs")->fetch();
page_start('งานซ่อม / แจ้งซ่อม');
?>
<div class="grid" style="grid-template-columns:repeat(3,1fr)"><div class="card stat-card"><div class="muted">งานทั้งหมด</div><div class="metric"><?=number_format($stats['total'])?></div></div><div class="card stat-card"><div class="muted">งานที่ยังไม่ปิด</div><div class="metric low"><?=number_format($stats['open_count'])?></div></div><div class="card stat-card"><div class="muted">ค่าใช้จ่ายรวม</div><div class="metric"><?=number_format($stats['cost_total'],2)?></div></div></div>
<div class="card"><div class="section-head"><div><h3><?= $edit?'แก้ไขงานซ่อม':'เปิดงานซ่อม' ?></h3><div class="muted">บันทึกอาการเสีย การแก้ไข และค่าใช้จ่าย</div></div></div><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=h($edit['id']??0)?>"><label>อุปกรณ์<select name="device_id" required><option value="">-- เลือกอุปกรณ์ --</option><?php foreach($devices as $d):?><option value="<?=$d['id']?>" <?=((int)($edit['device_id']??0)==$d['id'])?'selected':''?>><?=h($d['device_name'].' | '.$d['model'].' | '.$d['imei'])?></option><?php endforeach;?></select></label><label>หัวข้องานซ่อม<input name="title" required value="<?=h($edit['title']??'')?>"></label><label>สถานะ<select name="status"><?php foreach(['Open','In Progress','Waiting Parts','Completed','Cancelled'] as $st):?><option <?=($edit['status']??'Open')===$st?'selected':''?>><?=$st?></option><?php endforeach;?></select></label><label>ค่าใช้จ่าย<input type="number" step="0.01" min="0" name="cost" value="<?=h($edit['cost']??0)?>"></label><label style="grid-column:1/-1">อาการ / ปัญหา<textarea name="problem"><?=h($edit['problem']??'')?></textarea></label><label style="grid-column:1/-1">วิธีแก้ไข<textarea name="solution"><?=h($edit['solution']??'')?></textarea></label><label style="grid-column:1/-1">หมายเหตุ<textarea name="note"><?=h($edit['note']??'')?></textarea></label><div style="grid-column:1/-1"><button class="btn primary">บันทึก</button><?php if($edit):?> <a class="btn" href="/maintenance.php">ยกเลิก</a><?php endif;?></div></form></div>
<div class="card"><div class="section-head"><div><h3>ประวัติงานซ่อม</h3><div class="muted">ติดตามสถานะงานและค่าใช้จ่าย</div></div></div><div class="table-wrap"><table><thead><tr><th>งาน</th><th>อุปกรณ์</th><th>สถานะ</th><th>ค่าใช้จ่าย</th><th>ผู้แจ้ง</th><th>วันที่</th><th>จัดการ</th></tr></thead><tbody><?php foreach($jobs as $j):?><tr><td><strong><?=h($j['title'])?></strong><br><span class="muted"><?=h($j['problem'])?></span></td><td><?=h($j['device_name'])?><br><span class="muted"><?=h($j['model'].' '.$j['imei'])?></span></td><td><span class="badge <?=in_array($j['status'],['Completed'])?'success-bg':($j['status']==='Cancelled'?'danger-bg':'')?>"><?=h($j['status'])?></span></td><td><?=number_format((float)$j['cost'],2)?></td><td><?=h($j['full_name']??'-')?></td><td><?=h($j['created_at'])?></td><td><a class="btn small" href="/maintenance.php?edit=<?=$j['id']?>">แก้ไข</a><?php if(is_admin()):?><form method="post" style="display:inline" onsubmit="return confirm('ยืนยันการลบงานซ่อมนี้?')"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$j['id']?>"><button class="btn small danger">ลบ</button></form><?php endif;?></td></tr><?php endforeach;if(!$jobs):?><tr><td colspan="7" class="empty">ยังไม่มีงานซ่อม</td></tr><?php endif;?></tbody></table></div></div>
<?php page_end();
